export const questions = [
    {
      id: 1,
      question: 'ambulance',
      answer_a: "Amblance",
      answer_b: "Crane",
      answer_c:"Firetruck",
      answer_d: "Police Car",
      correct_answer: "a",
    },
    {
      id: 2,
      question: "crane",
      answer_a: "Amblance",
      answer_b: "Crane",
      answer_c:"Firetruck",
      answer_d: "Police Car",
      correct_answer: "b",
    },
    {
      id: 3,
      question: "firetruck",
      answer_a: "Amblance",
      answer_b: "Crane",
      answer_c:"Firetruck",
      answer_d: "Police Car",
      correct_answer: "c",
    },
    {
      id: 4,
      question: "police_car",
      answer_a: "Amblance",
      answer_b: "Crane",
      answer_c:"Firetruck",
      answer_d: "Police Car",
      correct_answer: "d",
    },
  ];
